[package]
name = "robosmith"
version = "2.1.0-Beta"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
songbird = "0.5.0"
sqlx = { version = "0.8.6", features = ["macros", "runtime-tokio", "sqlite"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
